title: sisyphus/
description: we must imagine sisyphus/ happy
remote_theme: pages-themes/modernist@v0.2.0

permalink: /:path/

exclude:
  - artifacts/
  - upstream/
  - .claude/
  - "*.sh"
  - Gemfile
  - Gemfile.lock
