# Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

theme = "congo"

baseURL = "https://tonyday567.github.io/"

defaultContentLanguage = "en"

enableRobotsTXT = true
summaryLength = 10
capitalizeListTitles = false
titleCaseStyle = "none"

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]

[privacy]
  [privacy.vimeo]
    enableDNT = true
  [privacy.x]
    enableDNT = true
  [privacy.youTube]
    privacyEnhanced = true

[services]
  [services.x]
    disableInlineCSS = true

[module]
  # Mount ~/mash/artifacts/ as /artifacts/ in the site
  # Allows referencing artifacts with /artifacts/image.svg in markdown
  [[module.mounts]]
    source = "content"
    target = "content"

  [[module.mounts]]
    source = "static"
    target = "static"

  [[module.mounts]]
    source = "layouts"
    target = "layouts"

  [[module.mounts]]
    source = "data"
    target = "data"

  [[module.mounts]]
    source = "assets"
    target = "assets"

  [[module.mounts]]
    source = "i18n"
    target = "i18n"

  [[module.mounts]]
    source = "archetypes"
    target = "archetypes"

  # Preview mounts: view any content from ~/mash/ as it would look on site
  # Access at http://localhost:1313/preview/mash/content/base/, /preview/mash/content/self/, etc.
  [[module.mounts]]
    source = "/Users/tonyday567/mash/content"
    target = "content/preview/mash/content"

  [[module.mounts]]
    source = "/Users/tonyday567/mash/ingest"
    target = "content/preview/mash/ingest"

